name: Build

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      postgres_db:
        image: postgres:14
          context: ./Docker
          dockerfile: db.Dockerfile
        volumes:
            - ./var/pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
#      - name: Create db
#        run: |
#          docker-compose -f docker-compose.yml up --no-start
#          docker-compose -f docker-compose.yml start
      - name: Maven Verify
        run: mvn -B clean verify