name: Build

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      postgres_db:
        image: postgres:14
        volumes:
          - docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: vbyfnj56
          POSTGRES_MULTIPLE_DATABASES: kacher, public
#          POSTGRES_DB: kacher
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
#        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
#      - name: Create db
#        run: |
#            psql -U postgres
#            psql -c "create database public"
      - name: Maven Verify
        run: mvn -B clean verify